name: Testing

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Julia 
        uses: julia-actions/setup-julia@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run Tests
        uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
